# SPDX-License-Identifier: MIT
"""Run the UDP seam cocotb tests under the project-local Verilator.

The seam is exercised against the real oca_core, not a stub, because the
property under test is that the header queue stays in step with the core's
responses -- and the one input that breaks that step is a request the core
answers with nothing at all (oca_proto.sv:779). A stub written from the same
reading of oca_proto as the seam would agree with the seam's mistakes.

Two modules therefore have to elaborate together, and cocotb takes one
toplevel, so the harness below is written into the build directory rather
than kept as a fourth source file. It is structure only -- two instances and
the wires between them -- and generating it keeps the parameters the tests
assume and the parameters the design is elaborated with from drifting apart.
"""

import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
VERILATOR_BIN = ROOT / "tools" / "verilator" / "bin"
RTL = ROOT / "oca" / "hw" / "rtl"

os.environ["PATH"] = str(VERILATOR_BIN) + os.pathsep + os.environ["PATH"]

try:
    from cocotb.runner import get_runner  # cocotb 1.x  # noqa: E402
except ModuleNotFoundError:
    from cocotb_tools.runner import get_runner  # cocotb 2.x  # noqa: E402
from cocotb_tools.check_results import get_results  # noqa: E402

SIM_DIR = Path(__file__).resolve().parent

# Imported by test_udp_seam.py rather than repeated there, so that a change to
# the elaboration cannot leave the expectations behind.
LOCAL_IP = 0xC0A80164
LOCAL_PORT = 5000
HDR_Q_DEPTH = 8
REPLY_TTL = 64

# The suite runs twice. At the shipping depth the queue must never fill, and
# the watermark says how much of it the worst traced case actually used. At
# depth 2 it must fill, which is the only way the guard -- hq_full stopping
# admission, and the drop landing on cnt_drop_full -- is executed at all
# rather than carried as unreachable code.
DEPTHS = (HDR_Q_DEPTH, 2)


def build_dir(depth: int) -> Path:
    return SIM_DIR / f"sim_build_udp_seam_d{depth}"

HARNESS = """// SPDX-License-Identifier: MIT
// GENERATED by run_udp_seam.py -- edit that file, not this one.
//
// Structure only: oca_udp_seam wired to oca_core. Every seam port is brought
// out so the testbench stands exactly where udp_complete_64 stands, and the
// core is reached only through the seam.
`default_nettype none

module tb_udp_seam (
    input  var logic        clk,
    input  var logic        rst_n,

    // Brought out so a test can assert that the address the stack answers
    // ARP for is the address the replies carry. On the board these are one
    // wire; here they are one wire the test can see.
    output var logic [31:0] stack_local_ip,

    input  var logic        rx_hdr_valid,
    output var logic        rx_hdr_ready,
    input  var logic [31:0] rx_ip_source_ip,
    input  var logic [15:0] rx_source_port,
    input  var logic [15:0] rx_dest_port,
    input  var logic [63:0] rx_payload_tdata,
    input  var logic [ 7:0] rx_payload_tkeep,
    input  var logic        rx_payload_tvalid,
    output var logic        rx_payload_tready,
    input  var logic        rx_payload_tlast,
    input  var logic        rx_payload_tuser,

    output var logic        tx_hdr_valid,
    input  var logic        tx_hdr_ready,
    output var logic [ 5:0] tx_ip_dscp,
    output var logic [ 1:0] tx_ip_ecn,
    output var logic [ 7:0] tx_ip_ttl,
    output var logic [31:0] tx_ip_source_ip,
    output var logic [31:0] tx_ip_dest_ip,
    output var logic [15:0] tx_source_port,
    output var logic [15:0] tx_dest_port,
    output var logic [15:0] tx_length,
    output var logic [15:0] tx_checksum,
    output var logic [63:0] tx_payload_tdata,
    output var logic [ 7:0] tx_payload_tkeep,
    output var logic        tx_payload_tvalid,
    input  var logic        tx_payload_tready,
    output var logic        tx_payload_tlast,
    output var logic        tx_payload_tuser,

    output var logic [31:0] cnt_accepted,
    output var logic [31:0] cnt_drop_short,
    output var logic [31:0] cnt_drop_port,
    output var logic [31:0] cnt_drop_full,
    output var logic [31:0] cnt_drop_nohdr,
    output var logic [31:0] cnt_tuser,
    output var logic [31:0] cnt_resp_orphan,
    output var logic [%(wm_hi)d:0] hdr_q_watermark
);

    logic [63:0] cs_tdata, cm_tdata;
    logic [ 7:0] cs_tkeep, cm_tkeep;
    logic        cs_tvalid, cs_tready, cs_tlast;
    logic        cm_tvalid, cm_tready, cm_tlast;

    oca_udp_seam #(
        .LOCAL_IP   (32'd%(local_ip)d),
        .LOCAL_PORT (16'd%(local_port)d),
        .REPLY_TTL  (8'd%(reply_ttl)d),
        .HDR_Q_DEPTH(%(depth)d)
    ) u_seam (
        .clk,
        .rst_n,
        .stack_local_ip,
        .rx_hdr_valid,
        .rx_hdr_ready,
        .rx_ip_source_ip,
        .rx_source_port,
        .rx_dest_port,
        .rx_payload_tdata,
        .rx_payload_tkeep,
        .rx_payload_tvalid,
        .rx_payload_tready,
        .rx_payload_tlast,
        .rx_payload_tuser,
        .tx_hdr_valid,
        .tx_hdr_ready,
        .tx_ip_dscp,
        .tx_ip_ecn,
        .tx_ip_ttl,
        .tx_ip_source_ip,
        .tx_ip_dest_ip,
        .tx_source_port,
        .tx_dest_port,
        .tx_length,
        .tx_checksum,
        .tx_payload_tdata,
        .tx_payload_tkeep,
        .tx_payload_tvalid,
        .tx_payload_tready,
        .tx_payload_tlast,
        .tx_payload_tuser,
        .core_s_tdata (cs_tdata),
        .core_s_tkeep (cs_tkeep),
        .core_s_tvalid(cs_tvalid),
        .core_s_tready(cs_tready),
        .core_s_tlast (cs_tlast),
        .core_m_tdata (cm_tdata),
        .core_m_tkeep (cm_tkeep),
        .core_m_tvalid(cm_tvalid),
        .core_m_tready(cm_tready),
        .core_m_tlast (cm_tlast),
        .cnt_accepted,
        .cnt_drop_short,
        .cnt_drop_port,
        .cnt_drop_full,
        .cnt_drop_nohdr,
        .cnt_tuser,
        .cnt_resp_orphan,
        .hdr_q_watermark
    );

    oca_core u_core (
        .clk,
        .rst_n,
        .s_axis_tdata (cs_tdata),
        .s_axis_tkeep (cs_tkeep),
        .s_axis_tvalid(cs_tvalid),
        .s_axis_tready(cs_tready),
        .s_axis_tlast (cs_tlast),
        .m_axis_tdata (cm_tdata),
        .m_axis_tkeep (cm_tkeep),
        .m_axis_tvalid(cm_tvalid),
        .m_axis_tready(cm_tready),
        .m_axis_tlast (cm_tlast)
    );

endmodule

`resetall
"""

SOURCES = [
    RTL / "chacha20.sv",
    RTL / "poly1305.sv",
    RTL / "chacha20_poly1305.sv",
    RTL / "oca_keystore.sv",
    RTL / "oca_pktbuf.sv",
    RTL / "oca_proto.sv",
    RTL / "oca_core.sv",
    RTL / "oca_udp_seam.sv",
]


def failed_tests() -> int:
    """Red tests in the run that just finished.

    runner.test() only inspects results.xml under pytest, and Verilator exits
    0 on $finish even with failing tests: without this check the process exits
    0 however the suite went, and anything driving these runners by exit code
    would call a red suite green.
    """
    num_tests, num_failed = get_results(SIM_DIR / "results.xml")
    if num_tests == 0:
        raise RuntimeError("results.xml records no tests")
    return num_failed


def lint() -> int:
    """Refuse -Wall findings in the seam before anything is simulated."""
    import subprocess
    proc = subprocess.run(
        [str(VERILATOR_BIN / "verilator"), "--lint-only", "-Wall",
         str(RTL / "oca_udp_seam.sv"), "--top-module", "oca_udp_seam"],
        capture_output=True, text=True)
    if proc.returncode != 0:
        print(proc.stdout + proc.stderr, flush=True)
        print("lint: FAILED", flush=True)
        return 1
    print("lint: ok", flush=True)
    return 0


def write_harness(depth: int) -> Path:
    out = build_dir(depth)
    out.mkdir(parents=True, exist_ok=True)
    path = out / "tb_udp_seam.sv"
    path.write_text(HARNESS % {"local_ip": LOCAL_IP, "local_port": LOCAL_PORT,
                               "reply_ttl": REPLY_TTL, "depth": depth,
                               "wm_hi": (depth - 1).bit_length()})
    return path


def run_at(depth: int) -> int:
    harness = write_harness(depth)
    runner = get_runner("verilator")
    runner.build(
        sources=SOURCES + [harness],
        hdl_toplevel="tb_udp_seam",
        build_dir=build_dir(depth),
        always=True,
    )
    (SIM_DIR / "results.xml").unlink(missing_ok=True)  # never grade a stale file
    os.environ["OCA_SEAM_DEPTH"] = str(depth)
    runner.test(
        hdl_toplevel="tb_udp_seam",
        test_module="test_udp_seam",
        test_dir=SIM_DIR,
        build_dir=build_dir(depth),
        extra_env={"OCA_SEAM_DEPTH": str(depth)},
    )
    failed = failed_tests()
    print(f"HDR_Q_DEPTH={depth}: {failed} failed", flush=True)
    return failed


def main() -> int:
    rc = lint()
    if rc != 0:
        return rc
    return 1 if sum(run_at(d) for d in DEPTHS) else 0


if __name__ == "__main__":
    sys.exit(main())
